version: '3'
services:
  nexus:
    image: sonatype/nexus3
    user: root
    restart: always
    container_name: nexus-server-base
    ports:
      - "8083:8081"
      - "8084:8084"
    volumes:
      - ./nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g
